gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "${tf_loadbalancer_subnet_name}"
