region_name = "West Europe"
region_code = "eu-west"
organization_name = "msg systems ag"
department_name = "Automotive Technology"
project_name = "CloudTrain"
stage = "dev"
cluster_name = "iacaksdef"
network_cidr = "10.17.0.0/16"